rhdtl78/NAStreamer

- components/layout/Footer.jsx
> [Front]푸터 수정

- components/layout/Footer.jsx
- components/layout/HeadDrawer.jsx
- components/layout/Header.jsx
- container/layout/Layout.jsx
- pages/example.jsx
- pages/explore.jsx
- pages/index.jsx
- pages/video.jsx
> [Front]Drawer 장착

- components/layout/Header.jsx
> header 스타일링

- components/layout/Header.jsx
- package.json
- yarn.lock
> [front]Header 다시 만들기

- pages/video.jsx
> [Front]video 마테리얼 제거

- components/layout/Footer.jsx
> [Front]Footer 색깔 회색으로 만들기 오탈자 수정

- actions/index.js
- package.json
- pages/uploader.jsx
- reducers/index.js
- reducers/reducer_upload.js
- routes/index.js
- store/index.jsx
- yarn.lock
> [Backend]리덕스 예시 파일 전달

- routes/api.js
- server.js
> [Backend]파일목록 전달

- pages/player.jsx
- routes/api.js
- server.js
> player 쿼리 문에 맞춰서 맞는 비디오 재생

- config/index.json
- models/index.js
- models/user.js
- package.json
- pages/signup.jsx
- routes/auth.js
- routes/passport/local-login.js
- routes/passport/local-signup.js
- server.js
- yarn.lock
> 로그인 기능 추가(passport)

- package.json
- store/index.jsx
- yarn.lock
> [Infra]Redux Dev Tool 사용.

- components/player/PlayerDiscription.jsx
- pages/player.jsx
> 플레이어 디스크립션 구성

- actions/index.js
- models/video.js
- routes/index.js
> uploader로 올릴때 디비에 저장하기

- container/login/LogInForm.jsx
- models/video.js
> 로그인시 에러메시지 나오게 하기

- components/VideoCard/VideoCard.jsx
- container/VideoCardList/VideoCardList.jsx
- pages/video.jsx
- routes/api.js
- server.js
> player연결할때 이제 video 디비 보고 주기

- components/VideoCard/VideoCard.jsx
- container/VideoCardList/VideoCardList.jsx
- pages/player.jsx
- routes/api.js
> player src 디비보고 하기

- components/player/PlayerDiscription.jsx
- config/index.json
- models/video.js
- pages/player.jsx
- pages/video.jsx
- routes/api.js
- routes/index.js
> player 목업 대신 진짜 데이터로 보여주기

- .gitignore
- config/index.json
- package.json
- pages/player.jsx
- server.js
- yarn.lock
> socketio 추가

- container/player/MyVideoPlayer.jsx
- routes/api.js
> 30초에 한번씩 자동저장

- routes/api.js
- routes/middleware/auth-check.js
> 재생했던 비디오 목록 전달

- components/layout/SidebarContent.jsx
> 사이드바 세부 조정

- actions/index.js
- container/uploader/SettingModal.jsx
- package-lock.json
- package.json
- pages/uploader.jsx
- routes/index.js
- yarn.lock
> 토스트 메시지로 모달 띄우기

- components/layout/Copyright.jsx
- components/layout/Footer.jsx
- container/layout/Layout.jsx
> 링크 오류 수정 footer fix , create copyright

- actions/index.js
- components/layout/Copyright.jsx
- components/layout/Footer.jsx
- container/layout/Layout.jsx
- container/uploader/SettingModal.jsx
- package-lock.json
- package.json
- pages/uploader.jsx
- routes/index.js
- yarn.lock
Fix Security Issues on packages
> Emergency Commit
